version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

    ports:
      - "3316:3306"
    volumes:
      - inventory_mysql_data:/var/lib/mysql # Changed to named volume
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  inventory_mysql_data: